### ISSUE TITLE
sag-spm-boot-winrm 

### ISSUE THREAD

**Issue by HMHansson** [SoftwareAG/sagdevops-templates#183]
Couple of issues:
- CCE scripts/powershell does not work well with passwords if they contain characters such as double-quote (") or colon (:). Double-quote must be passed as a tripple tick (""") as input to the provisioning command. Colons are parsed incorrectly by the powershell script:
$ruser=$PlainCredentials.Split(":")[0]
$rpass=$PlainCredentials.Split(":")[1]
should be replaced by:
$ruser,$rpass=$PlainCredentials -split ":",2
or alternatively passed into the powershell script as two separate variables

- Password passed into the provisioning CLI is written in clear text to the CCE wrapper log, and additionally stored in the batch script under /actions folder. This is not ok.

- the template.yaml does not include the http and https ports, which means that defaults are used (should be added). Same thing with the Administrator password.

**Comment by bpaskalev** [comment]
Absolutely correct about parameters.  Initial version of the powershell script contained all cli parameters like http/s ports for CCE and SPM as well as administrator password. I removed them for simplicity, but if you need that I will update the script

Regarding special characters in passwords in 10.5 we introduced in bootstrap installer option for providing base64 encoded version of administrator password, probably will need to update the powershell script with such option. Will think about that. 

Anyway if above issues are showstopper for a project, let me know.

**Comment by bpaskalev** [comment]
no reply log time
