### ISSUE TITLE
Error: IS use MySQL when mysql.cnf set to "lower_case_table_names = 0"

### ISSUE THREAD

**Issue by rosstang2565** [SoftwareAG/sagdevops-templates#230]
Can somebody replace SQL "INSERT component_event xxx" to "INSERT COMPONENT xxx"?

Why you create table script is uppercase table name "COMPONENT_EVENT" but insert SQL is "component_event"?
```
CREATE TABLE IF NOT EXISTS COMPONENT_EVENT COMPONENT_EVENT_ID bigint(20) NOT NULL AUTO_INCREMENT, ...
```
```
INSERT INTO component_event (component_event_id ...
```

**Comment by YanaSimeonova** [comment]
Installation guide states that when configuring mySQL lower_case_table_names param should be set to 1.
https://documentation.softwareag.com/webmethods/wmsuites/wmsuite10-5/SysReqs_Installation_and_Upgrade/compendium/index.html#page/install-upgrade-webhelp/to-prepare_databases_22.html

sag-db-mysql template is tested with the following parameters:
https://github.com/SoftwareAG/sagdevops-templates/blob/master/templates/sag-db-mysql/mysql.cnf

**Comment by rosstang2565** [comment]
No, I mean that someone can change "component_event" to "COMPONENT_EVENT".
Then you can support either "lower_case_table_names = 0" or "lower_case_table_names = 1".

After version 10.5, I can't find "component_event" in xx-ddl.sql and change that by manual.
So, my workaround is create "component_event" table before run dbConfigurator.sh.

Finally, my mysql table have "COMPONENT_EVENT" and "component_event" in the same time.
Now, my IS is running in "lower_case_table_names = 0".

**Comment by YanaSimeonova** [comment]
Ok, I see. But it is a limitation in the product and cannot be addressed as an issue in the templates samples.
Can you contact SAG global support so they can open a support incident and assign it to the respective team.
